### ISSUE TITLE
InvoicePayment amount has the wrong type

### ISSUE THREAD

**Issue by PatrikFomin** [FortnoxAB/csharp-api-sdk#82] opened 2020-04-24 20:39 UTC
I guess that the object InvoicePayment should have amount type set to decimal instead of string.

**Comment by richardrandak** [comment] 2020-04-27 10:38
Thanks for the feedback.
In old implementation all the types were strings. The issue is tracked already in #38 so i will close this one.
Please, try out the beta release version where all types were synced with the documentation and let me know if any other issues

**Closed by richardrandak** 2020-04-27 10:38 UTC
